_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.11.4
        t:
            "1":
                - 1
                - 2
                - 3
                - 5
                - 11
                - 12
                - 41
                - 49
                - 51
                - 53
                - 55
                - 75
            "2":
                - 1
                - 2
                - 3
                - 5
                - 11
                - 12
                - 41
                - 49
                - 51
                - 53
                - 55
                - 75
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.11.4
            "5": 0.19.11
            "6": 4.53.2
            "8":
                - 1
                - 3
                - 5
            "12": 0.19.11
            "13": windows-amd64
